language: ruby
rvm:
- 2.3.3
bundler_args: "--jobs=2"
script:
- bundle exec rake db:setup
- bundle exec rake spec
cache: bundler
services:
- postgresql
addons:
  postgresql: "9.4"
deploy:
  provider: heroku
  api_key:
    secure: k7ctBIDe8mYEKnscvCR/C2lQ3fAqD40nClw/qjI6ZnNgFa5YSxlGcC1E3AYjSsF6yIK/1jbJUwUOtV477gIybR+c0OE7pyHF0x0drVennEJHdHrIZX/MIVHSZ6pfRDTlNxnfeXudaRqsgvhe0gEdWajhpxAOxzDSGxlyQw5BsgCUq/vE6dvsHWLLvYX020W4vp+G+GGVRRNrA4LNx4DSo7/yjqdoYVYZdHpn+l6V06d3uxTmlk/2mqEqOxaSYn8v52YE1HKeelztddM6Wm1WGUuiijBJfVvUkJILQtoHOsxFw7jfyaW/o8yMCPqOK/UpBViZIppcnzOKD0tplOiAcJn7TAtwnKYN37PzFekyVoiU4chqUaxJRRv8P9Vs0HV1L9UufNk4iFkGpPj3KQpeSFDyAVnFPw52uTRki6OYkGANYF0mCaLTAC6o2ZM5E6HtJv8Tvj6+2k61r6nHKlE7UGNdiPjq4fTDU8l8hNBAu+ehQSmmmViE4T5r7imdqfZTcnTLemf/I9rHU9RlCfQzTOi2e/IKmEQ0kui2kqzFanhOrXL646xdXdKuunbY3JKjJKY4Qzin4+VDy7TOHKXyKI37LJJC/ZYwV6oCTWQRPmVy0tTZroYyL92U9xm8quFxhpACUhA8BrEtiaO5OQRQ0esYT8uqOIIRLtd7OisHFnk=
  app: rachapio12
