language: ruby
rvm:
- 2.3.3
bundler_args: "--jobs=2"
script:
- bundle exec rake db:setup
- bundle exec rake spec
cache: bundler
services:
- postgresql
addons:
  postgresql: '9.4'
deploy:
  provider: heroku
  api_key:
    secure: nAQM49i0MzMI1a+KcW3OBF38C81rVaqPslC48mu0opTv3ia4Ulys86fqhUnKI+6l4KSYB++m7lzaneVfptclmnSIKyL4zQFkfR9jfLZONy1AAhNxfy396UYjCkKW6hpjPgocap7ER2Cu6yWIJSSXdYbo8iPdbrm7G9H89iAMcS9XGdGrEVy/MDfede0w7j39aWT0opCPsewLT9EIKh44S4a03tDo/U7ame5Cl5CwTEuWd9kcrCLSxCo3BdvblW/D1H54d8f/I4436pt4Hg8ojhzBAcLiCB9u7d3TFWzo7ecqZNCm78prCye/cjIPw/8pNsRsg2JxBCuNBZdBp4I8zC7vRQPc23q1D/6++LVBTBq0GED4cpQZ1q0fg5qhVfE73v090pwcxLAIqCIfgh4zePzETlte5suNp8KHYuOZ9OxxPwxPVPSPCD+C2vjTasJuGEl8wqrRczcS5CITRVPG9V69+M7cCLIfW6vkDA8TZNUrhGGlli1NBEx+Z6VUvXpzctCPMiN5rkvTihb2bgWHctPOmWcFjmcqmsxEwurjAr1afHThdaw/2x4+9n6tLmDDwMnTtecQx0vMd7c2cFtBOShBDIOZFQa/Qqs8uuGfhpHFXddQATXxrU+He1iM5ogTNYBwvedn+3ovubMJHNTjkOYBu8RuV3ngoxzeWB2f6+k=
  app: rachapio12
