default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  pool: 20
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost
  database: rachapio12_development

test:
  <<: *default
  database: rachapio12_test

production:
  <<: *default
  database: rachapio12_production
  username: rachapio12
  password: <%= ENV['RUBY-RACHAPIO12_DATABASE_PASSWORD'] %>
